FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY SampleApp/FrontEnd/FrontEnd.csproj SampleApp/FrontEnd/
RUN dotnet restore SampleApp/FrontEnd/FrontEnd.csproj
COPY . .
RUN dotnet publish SampleApp/FrontEnd/FrontEnd.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "FrontEnd.dll"]