[build]
  base = "SampleApp/FrontEnd"
  command = "dotnet publish -c Release -o publish"
  publish = "publish/wwwroot"

[build.environment]
  DOTNET_VERSION = "10.0.401"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200